# Fichier de traduction, différent pour dialogue_en.py et dialogue_es.py

# Tiers des armes
Common_Tier='Commun'
Rare_Tier='Rare'
Hero_Tier='Heroïque'
Relic_Tier='Relique'
Arcanic_Tier='Arcanique'
Easter_Egg_Tier='Easter Egg'

# Les armes
Wooden_Shield_Name='Bouclier en bois'
Wooden_Shield_Description=''
Wooden_Sword_Name='Épée en bois'
Wooden_Sword_Description=''
Old_Grimoire_Name='Vieux grimoire'
Priest_Shield_Name='Bouclier du Prêtre'
Priest_Shield_Description=''
Blacksmith_Sword_Name='Épée du forgeron'
Blacksmith_Sword_Description=''
Magical_Tome_Name='Tome Magique'
Magical_Tome_Description=''
Faith_Shield_Name='Bouclier de la Foi'
Faith_Shield_Description=''
Michael_Sword_Name='Épée de Michael'
Michael_Sword_Descripion=''
Dantalion_Anti_Bible_Name='Anti-Bible de Dantalion'
Dantalion_Anti_Bible_Description=''
Troll_King_Shield_Name='Bouclier du Roi Troll'
Troll_King_Shield_Description=''
Conquerer_Sword_Name='Épée du Conquérant'
Conquerer_Sword_Description=''
Elf_King_Epitome_Name='PasLaMoindreIdéePourLaTraduction'
Elf_King_Epitome_Description=''
Purgatory_Door_Name='Porte du Purgatoire'
Purgatory_Door_Description=''
Divine_Light_Blade_Name='Lame Divine de Lumière'
Divine_Light_Blade_Description=''
Satan_Profecy_Name='Profécie de Satan'
Satan_Profecy_Description=''
Hugo_Wives_Name='Femmes à Hugo'
Hugo_Wives_Description=''
Paul_Cum_Shield_Name='Bouclier de Cum de Paul'
Paul_Cum_Shield_Description=''
Mael_Schlong_Name='Schlong de Mael'
Mael_Schlong_Description=''
Arty_Pride_Book_Name='Arty il est gay'
Arty_Pride_Book_Description=''

Welcome='Bienvenue à Trolland, ceci est un jeu de haute fantaisie uniquement sur console avec un bon scénario et pas mal de combats.'
