# Fichier de traduction, différent pour dialogue_fr.py et dialogue_en.py

# Tiers des armes
Common_Tier='Común'
Rare_Tier='Raro'
Hero_Tier='Heroico'
Relic_Tier='Reliquia'
Arcanic_Tier='Arcánico'
Easter_Egg_Tier='Easter Egg'

# Les armes
Wooden_Shield_Name='Escudo de Madera'
Wooden_Shield_Description=''
Wooden_Sword_Name='Espada de Madera'
Wooden_Sword_Description=''
Old_Grimoire_Name='Viejo Grimorio'
Old_Grimoire_Description=''
Priest_Shield_Name='Escudo del Sacerdote'
Priest_Shield_Description=''
Blacksmith_Sword_Name='Espada del Herrero'
Blacksmith_Sword_Description=''
Magical_Tome_Name='Tomo Mágico'
Magical_Tome_Description=''
Faith_Shield_Name='Escudo de la Fe'
Faith_Shield_Description=''
Michael_Sword_Name='Espada de Michael'
Michael_Sword_Description=''
Dantalion_Anti_Bible_Name='Anti-Biblia de Dantalión'
Dantalion_Anti_Bible_Description=''
Troll_King_Shield_Name='Escudo del Rey Troll'
Troll_King_Shield_Description=''
Conquerer_Sword_Name='Espada del Conquistador'
Conquerer_Sword_Description=''
Elf_King_Epitome_Name='NiReputisimaIdea'
Elf_King_Epitome_Description=''
Purgatory_Door_Name='Puerta del Purgatorio'
Purgatory_Door_Description=''
Divine_Light_Blade_Name='Cuchilla Divina de Luz'
Divine_Light_Blade_Description=''
Satan_Profecy_Name='Profecía de Satanás'
Satan_Profecy_Description=''
Hugo_Wives_Name='Esposas de Hugo'
Hugo_Wives_Description=''
Paul_Cum_Shield_Name='Escudo de Cum de Pol'
Paul_Cum_Shield_Description=''
Mael_Schlong_Name='Schlong de Mael'
Mael_Schlong_Description=''
Arty_Pride_Book_Name='Artur, déjate de Mariposeos'
Arty_Pride_Book_Description=''

Welcome="Bienvenido a Trolland, este es un juego de alta fantasía exclusivo para consola con una historia genial y muchas, muchas peleas."
